### ISSUE TITLE
test9

### ISSUE THREAD

**Issue by scharlottej13** [coiled/dask-community#515]

**Comment by jrbourbeau** [comment]
Just added a label to double check the new action kicked off properly and it did https://github.com/coiled/dask-community/actions/runs/1866366117. Next I'm going to close this issue to see where this ticket ends up on the board

**Comment by scharlottej13** [comment]
> Just added a label to double check the new action kicked off properly and it did https://github.com/coiled/dask-community/actions/runs/1866366117. Next I'm going to close this issue to see where this ticket ends up on the board

looks like closing it automatically moved it to 'done'!
