### ISSUE TITLE
Blog post describing new community efforts

### ISSUE THREAD

**Issue by ian-r-rose** [coiled/dask-community#76]
We'd like to write a blog post describing Coiled's new community-related efforts, including
* Discourse
* More issue monitoring
* Accessibility sprints, collaboration with Quansight
* Building connections with downstream users and projects

Part of this will be to help attract more people to join the team!

cc @scharlottej13 and @pavithraes for visibility

**Comment by ian-r-rose** [comment]
I think we're pretty slammed this week, but hopefully we could try to pick this up for next week

**Comment by pavithraes** [comment]
Sounds exciting!

**Comment by pavithraes** [comment]
The blog post has been published: [Introducing Coiled’s Dask Community Team](https://coiled.io/blog/introducing-coileds-dask-community-team/) 🎉

**Comment by ian-r-rose** [comment]
Woo! Nice work @pavithraes!
